version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile-api
    container_name: matchscore_api
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  fetcher:
    build:
      context: .
      dockerfile: dockerfile-fetcher
    container_name: matchscore_fetcher
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: matchscore_redis
    ports:
      - "6379:6379"

#  Servislerin başlama sırası: önce Redis başlar, sonra diğerleri.

